# Generated by Django 2.2.7 on 2019-11-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btre', '0002_auto_20191108_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='first_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='realtor',
            name='last_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
