# Generated by Django 2.2.7 on 2019-11-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltype', '0002_character_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
