# Generated by Django 2.2.7 on 2019-11-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltype', '0003_auto_20191107_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
